// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package state

import (
	"database/sql"
)

type Download struct {
	ID       int64
	QueueID  int64
	Url      string
	SavePath string
	State    string
}

type DownloadChunk struct {
	ID             int64
	RangeStart     int64
	RangeEnd       int64
	CurrentPointer int64
	DownloadID     int64
}

type Queue struct {
	ID            int64
	Name          string
	Directory     string
	MaxBandwidth  sql.NullInt64
	StartDownload string
	EndDownload   string
	RetryLimit    int64
}
