// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package state

import (
	"database/sql"
	"time"
)

type Download struct {
	ID       int64
	QueueID  int64
	Url      string
	SavePath string
	State    string
	Retries  int64
}

type DownloadChunk struct {
	ID             string
	RangeStart     int64
	RangeEnd       int64
	CurrentPointer int64
	DownloadID     int64
}

type Queue struct {
	ID            int64
	Name          string
	Directory     string
	MaxBandwidth  sql.NullInt64
	StartDownload time.Time
	EndDownload   time.Time
	RetryLimit    int64
	ScheduleMode  bool
}
