// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package state

import (
	"database/sql"
)

type Download struct {
	ID      int64
	QueueID int64
}

type Queue struct {
	ID            int64
	Name          string
	Directory     string
	MaxBandwidth  sql.NullInt64
	DownloadStart sql.NullString
	DownloadEnd   sql.NullString
	RetryLimit    int64
}
