version: "2"
sql:
  - engine: "sqlite"
    queries: "../internal/state/queries"
    schema: "../internal/state/schemas/"
    gen:
      go:
        package: "state"
        out: "../internal/state/"
        overrides:
          - column: "queues.start_download"
            go_type:
              type: "TimeValue"
          - column: "queues.end_download"
            go_type:
              type: "TimeValue"
